<a href="https://colab.research.google.com/github/feanor010/ML/blob/main/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [3]:
import numpy as np
print (np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
arr = np.zeros(10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((7), 7)


array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:

np.arange(10,101)[::2]

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
np.random.random_sample(10)[::-1]


array([0.20141162, 0.79934056, 0.12286897, 0.83632344, 0.50593217,
       0.95634068, 0.94995445, 0.76157103, 0.45002995, 0.4530855 ])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
arr = np.full((4,4),7)
np.fill_diagonal(arr, [1,2,3,4])
print(arr)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [8]:
np.full((5,5),[0,1,2,3,4])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [7]:
arr = np.random.random_sample((10,10))
arr = arr - arr.mean(axis = 1, keepdims = True)
arr

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [9]:
arr = np.random.random_sample((10,10))
arr = arr - np.median(arr,axis=0,keepdims=True)
print(arr)


[[ 0.33275604  0.26587393  0.12867387 -0.64929884 -0.06046552 -0.05133546
  -0.48149592  0.33902515 -0.09689293  0.36984163]
 [-0.30157509 -0.08424699  0.14871228  0.11133333  0.06046552 -0.42447371
  -0.43347468 -0.18529816 -0.28337538  0.0273081 ]
 [-0.05100447 -0.0135399   0.01098879 -0.03724347  0.10557102  0.05133546
   0.25852737  0.63019842 -0.039301   -0.0273081 ]
 [ 0.13414546 -0.44121919 -0.62267869 -0.41366741 -0.18639522 -0.06538612
  -0.30833079 -0.14706922  0.039301   -0.29564184]
 [-0.30191387  0.19949097  0.04052259  0.10781547  0.27433252  0.19474586
  -0.03852619  0.44080549 -0.14351922 -0.58242067]
 [ 0.33368655  0.0135399  -0.67451879  0.03724347 -0.40806518 -0.17989899
   0.03852619 -0.11836531  0.1056695  -0.13458641]
 [ 0.26067046 -0.39030447 -0.14613085  0.11758885  0.20161762  0.31743851
   0.2013458   0.11836531 -0.07354989  0.05566485]
 [-0.28279995  0.13894739 -0.05291024 -0.25899169 -0.14243735 -0.65718983
  -0.34068927 -0.1456749   0.479691   -0.43647338]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [17]:
arr = np.random.random_sample((5,5))
arr = np.concatenate((arr,arr.max(axis =1,keepdims=True),arr.min(axis =1,keepdims=True)),axis = 1)
print(arr)


[[0.57802525 0.14707741 0.25727537 0.32071001 0.73299054 0.73299054
  0.14707741]
 [0.22951575 0.61205641 0.20619603 0.33608369 0.90650893 0.90650893
  0.20619603]
 [0.96347606 0.59651929 0.54950643 0.3295322  0.82462686 0.96347606
  0.3295322 ]
 [0.26785523 0.54865401 0.80809921 0.26041998 0.66096289 0.80809921
  0.26041998]
 [0.10019451 0.07339354 0.3707305  0.3212982  0.80378013 0.80378013
  0.07339354]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [20]:
a =np.mat(np.arange(1,50)[1::2]).reshape(4,6)
b =np.mat(np.arange(1,50)[2::2]).reshape(6,4)
print(a*b)
print(np.linalg.inv(a*b))

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]
 [38 40 42 44 46 48]]
[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]
[[-3.66503876e+11  3.21853878e-04  1.09951163e+12 -7.33007752e+11]
 [-7.33007752e+11  2.19902326e+12 -2.19902326e+12  7.33007752e+11]
 [ 2.56552713e+12 -4.39804651e+12  1.09951163e+12  7.33007752e+11]
 [-1.46601550e+12  2.19902326e+12  0.00000000e+00 -7.33007752e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [22]:
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
