<a href="https://colab.research.google.com/github/feanor010/ML/blob/main/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print (np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
arr = np.zeros(10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((7), 7)


array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:

np.arange(10,101)[::2]

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [28]:
np.random.random_sample(10)[::-1]


array([0.20141162, 0.79934056, 0.12286897, 0.83632344, 0.50593217,
       0.95634068, 0.94995445, 0.76157103, 0.45002995, 0.4530855 ])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [58]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [51]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [64]:
arr = np.full((4,4),7)
np.fill_diagonal(arr, [1,2,3,4])
print(arr)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [67]:
np.full((5,5),[0,1,2,3,4])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [75]:
arr1 =np.random.random_sample((10,10))

print(arr1[0])


[0.00125189 0.43869155 0.96197147 0.8908102  0.76523937 0.63125987
 0.22018179 0.50504916 0.6213603  0.84390218]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.